[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "evolver"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "PyQt6",
    "qtawesome",
    "sounddevice",
    "tzdata",
    "vosk",
]

[project.optional-dependencies]
dev = ["pytest", "vulture"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
include = ["evolver*"]
namespaces = false
